- name: Generate and publish Eiffel Events
  # You may pin to the exact commit or the version.
  # uses: fdegir/ega@44ec1b723ccebd268bd99e204b36b46e903b1027
  uses: fdegir/ega@v24
  with:
    # URL to Eiffel REMReM Publish Service
    remrem_publish_service_url: 'http://188.95.231.225:8096/generateAndPublish'
